### PR TITLE
Use default ssl config fo HiveMQ client

### PR DESCRIPTION
**Pull request by Myshkouski**
See [#380](https://github.com/micronaut-projects/micronaut-mqtt/issues/380).

### CODE REVIEW

**Review by jeremyg484 — CHANGES_REQUESTED** [review]
@Myshkouski Thanks for submitting!

I think the code looks fine, but this needs a couple of additions before we can approve and merge it: 

1. There needs to be test coverage for this new path.

2. We should also include an update to the documentation that describes this option and the differences to setting the SSL configuration explicitly.

Would you be able to submit these needed updates to the PR? I'm happy to guide you along as needed.

**Comment by Myshkouski** [comment]
@sdelamo Please review the following changes:

> 1. There needs to be test coverage for this new path.

Seems SSL configuration for HiveMQ client is not covered at all. I added 2 test suites: 
- `test-suite-hivemq-mqttv5-graal-mtls` - test with `mqtt.client.ssl.*` properties ([f6670e3](https://github.com/micronaut-projects/micronaut-mqtt/pull/381/commits/f6670e3d99d486fbc9f30e891cc00fc4a0779be1));
- `test-suite-hivemq-mqttv5-graal-no-mtls` - test without `mqtt.client.ssl.*` properties ([4b02e52](https://github.com/micronaut-projects/micronaut-mqtt/pull/381/commits/4b02e527a04769536bc661e44f34666974377b32)).

Both are based on existing `test-suite-mqttv5-graal-ssl` test suite.

Now coverage for `io.micronaut.mqtt.hivemq.v5.client.Mqtt5ClientFactory#buildTransportConfig` looks like this:

image_2024-04-02_13-20-43

**Comment by Myshkouski** [comment]
> 2\. We should also include an update to the documentation that describes this option and the differences to setting the SSL configuration explicitly.

Documentation already provides description for `mqtt.client.server-uri` option as:
> mqtt.client.server-uri  | The URI of server to connect to as [schema]://[serverHost]:[serverPort].

We could explicitly add what values are allowed for `schema` - `tcp` or `ssl`.
I think no additional docs about using SSL by default is required (that was the point of [the issue](https://github.com/micronaut-projects/micronaut-mqtt/issues/380)).

**Comment by jeremyg484** [comment]
> Seems SSL configuration for HiveMQ client is not covered at all. I added 2 test suites:
> 
> * `test-suite-hivemq-mqttv5-graal-mtls` - test with `mqtt.client.ssl.*` properties ([f6670e3](https://github.com/micronaut-projects/micronaut-mqtt/pull/381/commits/f6670e3d99d486fbc9f30e891cc00fc4a0779be1));
> * `test-suite-hivemq-mqttv5-graal-no-mtls` - test without `mqtt.client.ssl.*` properties ([4b02e52](https://github.com/micronaut-projects/micronaut-mqtt/pull/381/commits/4b02e527a04769536bc661e44f34666974377b32)).

@Myshkouski Excellent, thank you!

**Comment by jeremyg484** [comment]
@Myshkouski I was more thinking of the [SSL Connections](https://micronaut-projects.github.io/micronaut-mqtt/latest/guide/#ssl) section of the docs. Is there anything we should explain differently there?

**Review by jeremyg484 — APPROVED** [review]

**Pull request merged**
