### PR TITLE
Bugfix WillMessage in HiveMqttClient

### PR DESCRIPTION
**Pull request by VytautasCapgemini**
Adding applyWillPublish() method at the end of the willMessageBuilder to make sure changes are published with the connect message.

Ref example here: https://github.com/hivemq/hivemq-mqtt-client/blob/bb5dee551e1e19edbc4d6a9b19037a616a05db4f/examples/src/main/java/com/hivemq/client/mqtt/examples/Mqtt5Features.java

### CODE REVIEW

**Comment by dstepanov** [comment]
Can you please add a test?

**Comment by VytautasCapgemini** [comment]
Any tips on where I can add this? Would love to get some help at least to start.

**Comment by dstepanov** [comment]
Can you create a test similar to https://github.com/micronaut-projects/micronaut-mqtt/blob/3.4.x/test-suite-utils/src/main/groovy/io/micronaut/mqtt/test/intercept/SimplePubSubSpec.groovy to reproduce it?

**Comment by VytautasCapgemini** [comment]
Not sure how to check that will message after disconnection, I think subscriber also uses same connection, when I disconnect client, subscriber also disconnects and is not able to get the message and assert that it got it.

Maybe any ideas on how to assert here? I see in external mqtt tools that will message is getting published.

**Comment by VytautasCapgemini** [comment]
Ok, I got tests to pass with second context that can verfiy that will message was applied.

**Comment by dstepanov** [comment]
Thanks!

**Pull request merged**
